subroutine GET_ID_LIST (stringa,rstring,ID)
  TYPE :: FLT
        SEQUENCE
        character* 32 :: NETWORK
        real          :: BASE_VOLTAGE
        character* 24 :: TEXTOS(5000)
        INTEGER       :: ID(5000)
        REAL          :: V(5000)
        integer       :: LENGTH
 END TYPE FLT

TYPE(FLT) hash(20)
COMMON /DATA_LIST_V/HASH 
character (*) stringa
character (*) rstring
integer j
INTEGER ID
integer i
i=1
do while  (TRIM(HASH(i).NETWORK) /= "")
    IF (  TRIM(HASH(i).NETWORK) == TRIM(stringa(1:LEN_TRIM(HASH(i).NETWORK)))  ) THEN
    rstring=stringa(LEN_TRIM(HASH(i).NETWORK)+1:LEN(stringa))
    ID=i
    return
    END IF

i=i+1
end do
end subroutine





RECURSIVE SUBROUTINE ADD_TO_LIST(DATA_LIST,STRING,CLOW,CHI,ID )

!ESTRUCTURAS DE DATOS
   TYPE :: FLT
        SEQUENCE
        character* 32 :: NETWORK
        real          :: BASE_VOLTAGE
        character* 24 :: TEXTOS(5000)
        INTEGER       :: ID(5000)
        REAL          :: V(5000)
        integer       :: LENGTH
 END TYPE FLT
 TYPE(FLT) hash(20)
 COMMON /DATA_LIST_V/HASH 

INTEGER CLOW,CHI,HI,ID
INTEGER DATA_LIST
CHARACTER *24 STRING

INTEGER ULIMIT
INTEGER CMID
HI=HASH(DATA_LIST)%LENGTH

IF ((CHI-CLOW)<=3) THEN
 !BUSCA SI ES MENOR O MAYOR ETC
 ULIMIT=CHI

DO I=CLOW,ULIMIT
DO J=1,24
IF (   ICHAR(STRING(j:J))>ICHAR(HASH(DATA_LIST)%TEXTOS(I)(J:J)) ) THEN
X=I+1
GOTO 30 
END IF
IF (   ICHAR(STRING(J:J))<ICHAR(HASH(DATA_LIST)%TEXTOS(I)(J:J)) ) THEN
X=I
GOTO 90
END IF
END DO  
PAUSE
30 END DO  
!MUEVE TODO DESDE HI HASTA X


90 DO I=X,HI

HASH(DATA_LIST)%TEXTOS((HI+1-I)+X)=HASH(DATA_LIST)%TEXTOS((HI-I)+X)
HASH(DATA_LIST)%ID((HI+1-I)+X)=HASH(DATA_LIST)%ID((HI-I)+X)
!textos(DATA_LIST,(HI+1-I)+X)=textos(DATA_LIST,(HI-I)+X)
END DO
HASH(DATA_LIST)%ID(X)=ID
HASH(DATA_LIST)%TEXTOS(X)=STRING
HASH(DATA_LIST).LENGTH=HASH(DATA_LIST).LENGTH+1
!textos(DATA_LIST,X)=STRING
RETURN 




END IF
!TOMA LA MITAD Y VE SI ESTA EN ESTE RANGO
CMID=(CHI-CLOW)/2+1
CMID=CMID+CLOW-1


DO J=1,24
IF (   ICHAR(STRING(j:J))>ICHAR(HASH(DATA_LIST)%textos(CMID)(J:J)) ) THEN
CALL ADD_TO_LIST(DATA_LIST,STRING,CMID,CHI,ID )
GOTO 60 
END IF
IF (   ICHAR(STRING(J:J))<ICHAR(HASH(DATA_LIST)%textos(CMID)(J:J)) ) THEN
CALL ADD_TO_LIST(DATA_LIST,STRING,CLOW,CMID,ID )
GOTO 60
END IF
END DO 


60 RETURN
END SUBROUTINE







RECURSIVE SUBROUTINE FIND_IN_LIST(DATA_LIST,STRING,CLOW,CHI,POS )
   TYPE :: FLT
        SEQUENCE
        character* 32 :: NETWORK
        real          :: BASE_VOLTAGE
        character* 24 :: TEXTOS(5000)
        INTEGER       :: ID(5000)
        REAL          :: V(5000)
        integer       :: LENGTH
 END TYPE FLT
 TYPE(FLT) hash(20)
 COMMON /DATA_LIST_V/HASH 
 
INTEGER CLOW,CHI,HI,POS
INTEGER DATA_LIST
CHARACTER *24 STRING
INTEGER ULIMIT
INTEGER CMID

HI=HASH(DATA_LIST)%LENGTH

IF ((CHI-CLOW)<=3) THEN
ULIMIT=CHI
    DO I=CLOW,ULIMIT
        IF (STRING==HASH(DATA_LIST)%textos(I)) THEN
            POS=I
            RETURN 
        END IF
    END DO
POS=0
RETURN
END IF
!TOMA LA MITAD Y VE SI ESTA EN ESTE RANGO
CMID=(CHI-CLOW)/2+1
CMID=CMID+CLOW-1

IF (STRING==HASH(DATA_LIST)%textos(CMID)) THEN
    POS=CMID
    RETURN 
END IF

DO J=1,24
    IF (   ICHAR(STRING(j:J))>ICHAR(HASH(DATA_LIST)%textos(CMID)(J:J)) ) THEN
        CALL FIND_IN_LIST(DATA_LIST,STRING,CMID,CHI,POS )
        GOTO 60 
    END IF
    IF (   ICHAR(STRING(J:J))<ICHAR(HASH(DATA_LIST)%textos(CMID)(J:J)) ) THEN
        CALL FIND_IN_LIST(DATA_LIST,STRING,CLOW,CMID,POS )
        GOTO 60
    END IF
END DO 
wRITE (*,*) 'ERROR DESCONOCIDO EN BUSQUEDA'
60 RETURN
END SUBROUTINE